version: '3'

services:
  db:
    image: mariadb:10.5
  web:
    build: .
    # command: python3 manage.py runserver 0.0.0.0:8000
    command: sleep infinit
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db